apiVersion: v1
description: teamspeak
engine: gotpl
home: https://github.com/ksandermann/teamspeak-helm-chart
keywords:
- teamspeak
maintainers:
- email: kevin.sandermann@gmail.com
  name: ksandermann
name: teamspeak
sources:
- https://github.com/ksandermann/teamspeak-helm-chart
version: 0.1.1
appVersion: 3.12.0
