image:
  repository: teamspeak
  tag: 3.12.0
  pullPolicy: Always
  # Secret must be manually created in the namespace.
  # pullSecret: "nexus-pull-secret"
podAnnotations: {}
#only NodePort and LoadBalancer supported, as this is UDP traffic
service:
  type: LoadBalancer
  nodePort: 30987
resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  # existingClaim:
  # annotations:
  #  "helm.sh/resource-policy": keep
  #storageClass: "azure-managed-ssd"
  #storageSize: 2Gi
